services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      - DATABASE_URL=postgresql+asyncpg://${DB_USER}:${DB_PASS}@${DB_HOST}:${DB_PORT}/${DB_NAME}
      - PYTHONPATH=/app/src
    ports:
      - "8000:8000"
    env_file:
      - ../.env

